title:             Dev Spot
email:             ahnsv@bc.edu
description:       Learn, memorize, and share
author:            Humphrey Ahn
baseurl:           "/"
url:               "http://ahnsv.github.io"

# Social Profiles
twitter_username:  ahnsv
github_username:   ahnsv
facebook_username: sangtae.ahn

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
